<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ../assets/Zzeit.glb --types
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	ref = new Group();

	type ActionName = 'MoveForwardAnim';
	type GLTFResult = {
		nodes: {
			tyreflring: THREE.Mesh;
			tyreflrubber: THREE.Mesh;
			tyrefrring: THREE.Mesh;
			tyrefrrubber: THREE.Mesh;
			tyrerlring: THREE.Mesh;
			tyrerlrubber: THREE.Mesh;
			tyrerrring: THREE.Mesh;
			tyrerrrubber: THREE.Mesh;
			body: THREE.Mesh;
			head_lights: THREE.Mesh;
			interior: THREE.Mesh;
			lights_side: THREE.Mesh;
			tail_lights: THREE.Mesh;
			windows: THREE.Mesh;
		};
		materials: {
			['rim_vertica.004']: THREE.MeshStandardMaterial;
			['04 - Default.004']: THREE.MeshStandardMaterial;
			['rim_vertica.007']: THREE.MeshStandardMaterial;
			['04 - Default.007']: THREE.MeshStandardMaterial;
			['rim_vertica.005']: THREE.MeshStandardMaterial;
			['04 - Default.005']: THREE.MeshStandardMaterial;
			['rim_vertica.006']: THREE.MeshStandardMaterial;
			['04 - Default.006']: THREE.MeshStandardMaterial;
			paintMain: THREE.MeshStandardMaterial;
			wire_000000000: THREE.MeshStandardMaterial;
			['12___Car_Paint']: THREE.MeshStandardMaterial;
			phong1SG: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/Zzeit.glb');

	export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref);
</script>

<T is={ref} dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="mainempty" position={[0, 3.26, 0]} scale={1.72}>
				<T.Mesh
					name="tyreflring"
					geometry={gltf.nodes.tyreflring.geometry}
					material={gltf.materials['rim_vertica.004']}
					position={[1.09, -1.46, 1.89]}
					rotation={[0, 0, 0.06]}
					scale={1.46}
				>
					<T.Mesh
						name="tyreflrubber"
						geometry={gltf.nodes.tyreflrubber.geometry}
						material={gltf.materials['04 - Default.004']}
						position={[-0.75, -0.25, -1.3]}
					/>
				</T.Mesh>
				<T.Mesh
					name="tyrefrring"
					geometry={gltf.nodes.tyrefrring.geometry}
					material={gltf.materials['rim_vertica.007']}
					position={[-1.15, -1.43, 1.89]}
					rotation={[0, 0, 3.08]}
					scale={1.46}
				>
					<T.Mesh
						name="tyrefrrubber"
						geometry={gltf.nodes.tyrefrrubber.geometry}
						material={gltf.materials['04 - Default.007']}
						position={[-0.79, 0.24, -1.3]}
					/>
				</T.Mesh>
				<T.Mesh
					name="tyrerlring"
					geometry={gltf.nodes.tyrerlring.geometry}
					material={gltf.materials['rim_vertica.005']}
					position={[1.14, -1.45, -1.34]}
					scale={1.46}
				>
					<T.Mesh
						name="tyrerlrubber"
						geometry={gltf.nodes.tyrerlrubber.geometry}
						material={gltf.materials['04 - Default.005']}
						position={[-0.78, -0.25, 0.92]}
					/>
				</T.Mesh>
				<T.Mesh
					name="tyrerrring"
					geometry={gltf.nodes.tyrerrring.geometry}
					material={gltf.materials['rim_vertica.006']}
					position={[-1.19, -1.46, -1.34]}
					rotation={[0, 0, -Math.PI]}
					scale={1.46}
				>
					<T.Mesh
						name="tyrerrrubber"
						geometry={gltf.nodes.tyrerrrubber.geometry}
						material={gltf.materials['04 - Default.006']}
						position={[-0.82, 0.24, 0.92]}
					/>
				</T.Mesh>
			</T.Group>
			<T.Mesh
				name="body"
				geometry={gltf.nodes.body.geometry}
				material={gltf.materials.paintMain}
				position={[0, 0.19, 0]}
			>
				<T.Mesh
					name="head_lights"
					geometry={gltf.nodes.head_lights.geometry}
					material={gltf.materials.wire_000000000}
				/>
				<T.Mesh
					name="interior"
					geometry={gltf.nodes.interior.geometry}
					material={gltf.materials.paintMain}
				/>
				<T.Mesh
					name="lights_side"
					geometry={gltf.nodes.lights_side.geometry}
					material={gltf.materials.wire_000000000}
				/>
				<T.Mesh
					name="tail_lights"
					geometry={gltf.nodes.tail_lights.geometry}
					material={gltf.materials['12___Car_Paint']}
				/>
				<T.Mesh
					name="windows"
					geometry={gltf.nodes.windows.geometry}
					material={gltf.materials.phong1SG}
				/>
			</T.Mesh>
		</T.Group>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T>
